### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by bbean23**
Sorry, I forgot that we should be developing on the "develop" branch....

### CODE REVIEW

**Comment by braden6521** [comment]
I'm assuming that these are all the changes that have been previously reviewed, but accidentally went to main instead of develop? If so, this looks good to me. And I'm sorry, I should have caught that during my reviews too.

**Review by braden6521 — APPROVED** [review]

**Comment by e10harvey** [comment]
Thank you for these changes, @bbean23. I would prefer that we rebase instead.

**Comment by bbean23** [comment]
@e10harvey I'm good with rebasing. Is there a way to do that through github? Or do I do that locally and then force push?

**Comment by e10harvey** [comment]
> @e10harvey I'm good with rebasing. Is there a way to do that through github? Or do I do that locally and then force push?

I would rebase on top of upstream main locally and then force push to bbean23:develop.

**Pull request closed without merging**
