### PR TITLE
.github/workflows: Added format.yml, fixed pep8 violations

### PR DESCRIPTION
**Pull request by e10harvey**

### CODE REVIEW

**Comment by e10harvey** [comment]
Reviewers: Please do no worry about reviewing the changes in https://github.com/sandialabs/OpenCSP/pull/34/commits/6823cc8fc7f6a59fe05b384daed27f5fec1fa2b5 as they are all formatting changes.

**Comment by braden6521** [comment]
Was this the CI check that we were going to add suggestions from Ben in a settings file? Or would this go somewhere else?

For reference:
max_line_length = 120
ignore = E224,E226,E721,E731

**Comment by e10harvey** [comment]
> Was this the CI check that we were going to add suggestions from Ben in a settings file? Or would this go somewhere else?
> 
> For reference: max_line_length = 120 ignore = E224,E226,E721,E731

That is correct. I added the line length suggestion via https://github.com/sandialabs/OpenCSP/pull/34/commits/0b979884cd2d699f93110dabeb6884ea6849192f but am not sure how to add the equivalent of `ignore = E224,E226,E721,E731`. Hopefully that is acceptable or perhaps we can team up on adding `ignore = E224,E226,E721,E731`.

**Review by braden6521 — APPROVED** [review]
Looks good to me then!

**Pull request merged**
