### PR TITLE
54 testmemorymonitor test large memory usage unit test failing

### LINKED ISSUE #54: TestMemoryMonitor test_large_memory_usage unit test failing
The following is output in the ubi-8 unit tests when running TestMemoryMonitor::test_large_memory_usage

```
common/lib/process/test/test_MemoryMonitor.py::TestMemoryMonitor::test_large_memory_usage 
Error: Process completed with exit code 134.
```

### PR DESCRIPTION
**Pull request by bbean23**
This has somehow fixed #54. I'm not entirely sure what the issue was. My guess is that this fixes it because this reduces the possible interaction surface area between the garbage collector and the multiprocessing queue.

### CODE REVIEW

**Comment by bbean23** [comment]
closes #54

**Review by e10harvey — CHANGES_REQUESTED** [review]
@bbean23, thank you for these changes. In general, everything looks great. I do not understand what's causing the bug and need to before attempting to review a fix.

Do you have time to determine the cause of the bug with me today?

Should the test be disabled until the bug is resolved so that others can proceed with their PRs?

**Comment by braden6521** [comment]
@e10harvey's reasoning makes sense. Understanding the problem well before fixing makes sense to me. I'm on board with skipping in the meantime.

**Comment by bbean23** [comment]
As determined during our call today, the MemoryMonitor class has been removed, to be replaced with a third party tool like "top" on an as-needed basis.

**Review by braden6521 — APPROVED** [review]
Feel free to Merge! Thanks for doing this!

**Pull request merged**
